# Generated by Django 4.1.5 on 2023-01-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20230111_1630"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
    ]
